spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: 1995
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
